version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/pfa
      - PORT=3000
    ports:
      - "3000:3000"
volumes:
  mongo-data:
